### ISSUE TITLE
implement dynamic path depending on a screen size

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#268]
it should be <engine name>/<cluster name>/<vm_name> instead

**Comment by suomiy** [comment]
should be fixed, can you recheck all the paths please? Especially when creating/editing triggers from main/vm activity

**Comment by shiramax** [comment]
it look OK..only that if the name of the cluster is too long , in the VM  window , the name of the cluster will presented with 2 dots, (for example : Vioelt/golden_en../vm1)  I guess that this is normal behaviour when the screen is too small, 
but when the device  is vertical , then it should be possible to see the all cluster name.
![image](https://cloud.githubusercontent.com/assets/5609929/26825451/bcf12f18-4abd-11e7-8dd6-4684511b1ee2.png)

**Comment by suomiy** [comment]
it is hardcoded for now. If the path component is larger than 10 characters then it will be truncated except for the last component. We could make it work, but the code for that would be quite hacky. I will ask Tomas what is the right course.

**Comment by jelkosz** [comment]
I think it is good enough for navigation even though I see your point. 
So I would leave this bug opened for now and get back to it eventually, but did not try to chase it to the upcoming release.

**Comment by suomiy** [comment]
I will just put a note for the future here. Because the characters can have various width we do not know how many characters we can display beforehand.

So for one string we can try binary division and check each time if the string can be fit to the screen. The trick is to do that for multiple components at once.

Probably easier way to implement is to increment each component by one character until it fits the whole screen while leaving the last component  reasonably long.
